name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Attempt to compile
        run: yarn tsc --version && yarn tsc

      - name: Run tests
        run: yarn test

      - name: Enforce linting
        run: yarn lint
